services:

  # ---------- PostgreSQL for Auth ----------
  postgres-auth:
    image: postgres:15
    container_name: postgres-auth
    environment:
      POSTGRES_USER: authentication
      POSTGRES_PASSWORD: authentication123
      POSTGRES_DB: authentication
    ports:
      - "5432:5432"
    volumes:
      - postgres_auth_data:/var/lib/postgresql/data
    networks:
      - app-net

  # ---------- Authentication Service ----------
  authentication:
    build: ./authentication
    container_name: authentication
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-auth:5432/authentication
      SPRING_DATASOURCE_USERNAME: authentication
      SPRING_DATASOURCE_PASSWORD: authentication123
    depends_on:
      - postgres-auth
    networks:
      - kafka-net
      - app-net
      - elk-net

  # ---------- PostgreSQL for Stock ----------
  postgres-stock:
    image: postgres:15
    container_name: postgres-stock
    environment:
      POSTGRES_USER: stock
      POSTGRES_PASSWORD: stock123
      POSTGRES_DB: stock   # DB ismi stock olarak değişti
    ports:
      - "5433:5433"
    volumes:
      - postgres_stock_data:/var/lib/postgresql/data

  # ---------- Stock Service ----------
  stock:
    build: ./stock
    container_name: stock
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-stock:5433/stock
      SPRING_DATASOURCE_USERNAME: stock
      SPRING_DATASOURCE_PASSWORD: stock123
    depends_on:
      - postgres-stock

  # ---------- PostgreSQL for Notification ----------
  postgres-notification:
    image: postgres:15
    container_name: postgres-notification
    environment:
      POSTGRES_USER: notification
      POSTGRES_PASSWORD: notification123
      POSTGRES_DB: notification
    ports:
      - "5434:5432"
    volumes:
      - postgres_notification_data:/var/lib/postgresql/data
    networks:
      - app-net

  # ---------- Notification Service ----------
  notification:
    build: ./notification
    container_name: notification
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-notification:5432/notification
      SPRING_DATASOURCE_USERNAME: notification
      SPRING_DATASOURCE_PASSWORD: notification123
    depends_on:
      - postgres-notification
    networks:
      - kafka-net
      - app-net
      - elk-net

  zookeeper:
    image: wurstmeister/zookeeper
    container_name: zookeeper
    ports:
      - "2181:2181"
    networks:
      - kafka-net
  kafka:
    image: wurstmeister/kafka
    container_name: kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_LISTENERS: INSIDE://kafka:9092,OUTSIDE://localhost:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INSIDE:PLAINTEXT,OUTSIDE:PLAINTEXT
      KAFKA_LISTENERS: INSIDE://0.0.0.0:9092,OUTSIDE://0.0.0.0:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INSIDE
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CREATE_TOPICS: "baeldung:1:1"
    networks:
    - kafka-net
  mailhog:
    image: mailhog/mailhog
    ports:
      - "1025:1025"
      - "8025:8025"
    networks:
      - app-net

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.13.2-arm64
    container_name: elasticsearch
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    ports:
      - "9200:9200"
    networks:
      - elk-net

  kibana:
    image: docker.elastic.co/kibana/kibana:8.13.2-arm64
    container_name: kibana
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
    networks:
      - elk-net
    
networks:
  kafka-net:
    driver: bridge
  app-net:
    driver: bridge
  elk-net:
    driver: bridge


volumes:
  postgres_auth_data:
  postgres_stock_data:
  postgres_notification_data:
